all:
	g++ main.cpp lib/vec2/vec2.cpp lib/entityManager/entity_manager.cpp lib/entity/entity.cpp lib/gameEngine/game_engine.cpp -I/opt/homebrew/Cellar/sfml/3.0.0_1/include/ -std=c++17 -o assigment2 -L/opt/homebrew/Cellar/sfml/3.0.0_1/lib/ -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio && ./assigment2
